# Generated by Django 5.1.4 on 2025-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experiece",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
