# Generated by Django 5.1.4 on 2025-01-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_search", "0002_job_experiece"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experiece",
            field=models.IntegerField(verbose_name=0),
        ),
    ]
